"""Holds the basic information about the exploration.
"""

Ns = [2, 4, 8, 16]
tech_nodes = [16, 7, 5, 4, 3.1, 3.0]
seeds = [50936, 25124, 43033]
#Generated by random.randint(1, 65536) on 16.08.19 at 19:10

#NOTE: Minimum grid sizes. Found by >>grid_sizer/size.py<<. 
grid_sizes =\
    {2: {'spla': 42,\
         'diffeq': 23,\
         'clma': 59,\
         'ex5p': 22,\
         's38584.1': 49,\
         'seq': 28,\
         'ex1010': 42,\
         's38417': 44,\
         'apex2': 30,\
         's298': 28,\
         'apex4': 25,\
         'elliptic': 36,\
         'alu4': 27,\
         'tseng': 24,\
         'pdc': 46,\
         'frisc': 41,\
         'misex3': 27},\
     4: {'spla': 30,\
         'diffeq': 18,\
         'clma': 42,\
         'ex5p': 16,\
         's38584.1': 36,\
         'seq': 21,\
         'ex1010': 31,\
         's38417': 32,\
         'apex2': 22,\
         's298': 21,\
         'apex4': 18,\
         'elliptic': 26,\
         'alu4': 20,\
         'tseng': 17,\
         'pdc': 33,\
         'frisc': 30,\
         'misex3': 20},\
     8: {'spla': 22,\
         'diffeq': 13,\
         'clma': 31,\
         'ex5p': 12,\
         's38584.1': 26,\
         'seq': 16,\
         'ex1010': 23,\
         's38417': 23,\
         'apex2': 16,\
         's298': 15,\
         'apex4': 14,\
         'elliptic': 19,\
         'alu4': 15,\
         'tseng': 13,\
         'pdc': 24,\
         'frisc': 22,\
         'misex3': 15},\
     16: {'spla': 17,\
          'diffeq': 10,\
          'clma': 23,\
          'ex5p': 10,\
          's38584.1': 20,\
          'seq': 12,\
          'ex1010': 17,\
          's38417': 18,\
          'apex2': 13,\
          's298': 12,\
          'apex4': 10,\
          'elliptic': 15,\
          'alu4': 11,\
          'tseng': 10,\
          'pdc': 18,\
          'frisc': 17,\
          'misex3': 11},\
    }
